This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file ./manual.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file manual.acn....done (23 entries accepted, 0 rejected).
Sorting entries....done (102 comparisons).
Generating output file manual.acr....done (25 lines written, 0 warnings).
Output written in manual.acr.
Transcript written in manual.alg.
